### Introduction in OOP in pyhton


```one of the popular approach to slove a programming problem by creating an objects.This is known as object oriented programming 
 
 
 An object has two characteristics:
 
 1. attributes (name,age,colour)
 2. behaviour (learn,study,singing,dancing)
 
 
 In python,the concept OOP follow these things:
 1. Inheritance
 2.encapsulation
 3.ploymorphism
 
 class:
 
 A class is blueprint for the object

 Object:
 
 blue print of class or instance of the class or physical entity
 
 methods:
 
 part of class and can be called with object
 
```



In [0]:
class classname:
  #some functions and variables
  # function --- used to perform the specific activity
  #variable--data(memory)

In [0]:
#this is function
def test():
  return

In [0]:
#this is a method
class Demo1:
  def fact(self,n):
    #return the factorial
    fact=1
    while(n!=0)
     fact=fact*n
      n=n-1
  return fact
  
p1=demo1()
print()

  

In [0]:
class Demo2:
  def Accept(self,p1,p2):
    self.p1=p1
    self.p2=p2
    
    return
  
  def display(self):
    print("a=",a)
    print("b=",b)
    
c1=Demo2()
c1.Accept(10,20)
c1.display()

In [0]:
class Demo2:
  def _init_(self,p1,p2):
    self.p1=p1
    self.p2=p2
    
  def add(self,p1,p2):
    return p1+p2
  
c1=Demo2()
print(c1.add(100,200))

300


In [0]:
#some inheritance 
#parent class
class person(object):
  #construction
  def _init_(self,name):
      self.name=name
  def getname(self):
      return self.name
  def isemployee(self):
      return False
  
 #derived class
class employee(person):
  def isemployee(self):
    return True
  
emp= person("chandana")
print(emp.getname(),emp.isemployee())

emp1 =employee("harshi")
print(emp.getname(),emp1.isemployee)
  
  

TypeError: ignored

### Python Numpy

NumPy arrays is a bit like python list 
numPy array iscentral data structure of the numpy lib
this lib is actually short for "numeric python" or "" numeric python"

In [0]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(lst)
print(array.shape)
print(array.dtype)

[1, 2, 3, 4]
(4,)
int64


In [0]:
a1=np.array([(1,2,3),(4,5,6,)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)


(2, 3)
(3, 2)


In [0]:
# re-shape the given array
#numby.reshape(array)name,reshape,order='c')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)


[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
#append some data ----horizontally
#append some data------vertically
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))



[1 2 3 4 5 6]


In [0]:
#generate random number from NP
a1=np.random.normal(5,0,15,10)
print(a1)


TypeError: ignored

In [0]:
np.zeros((2,2))
np.zeros((2,2),dtype=np.int

SyntaxError: ignored

In [0]:
np.ones((4,3),dtype=np.int64)


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [0]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [0]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)


[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [0]:
#arrange() - - - particular
#numpy,arrange(start,end)
#end---- vaue
#step----gap between one value to another value 
import numpy as np
np.arrange(1,10,2)


AttributeError: ignored

In [0]:
a1=np.array([(1,2,3),(4,5,6,)])
print("second column:",a1[:,2])

second column: [3 6]


In [0]:
  a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[0])

first row: [1 2 3]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column:",a1[:,1])

slicing column: [2 5]


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print("silcing row:",a1[:,1])

silcing row: [2 5]


In [0]:
#some mATH OPERATION given random numbers
#min-----returns the least number 
#max----returns the largest number
#mean-----mean
#median----median
a1=np.random.normal(5,1,10)
print(a1)
print("Min value=",np.min(a1))
print("Max value=",np.max(a1))
print("Mean value=",np.mean(a1))
print("Median value=",np.median(a1))

[6.6769644  4.67100815 4.96800496 4.98859639 5.83017067 5.68084398
 3.57601837 3.63061181 4.08262572 5.69095038]
Min value= 3.5760183686362224
Max value= 6.676964396546721
Mean value= 4.979579481628765
Median value= 4.978300672210489


In [0]:
#muliply of 1D array
#numpy.dot(x,y)--
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)


14

In [0]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

### pandas basics
panda dataframes

Data analysis with python
 
 
 python is one of the popular programming language for data analysis
 
 python is offering the lib called pandas


In [0]:
import pandas as pd
dict = {"Name":["hitesh","chandu","akhil","pk","megastar","Tan"],
      "EmailID":["hitesh@gmail.com","chandu2000@gmail.com","akhil@gmail.com","pk@gmail.com","mega@gmail.com","tan@gmail.com"],
       "MobileNumber":[999,888,777,555,222,111],
       "Address":["Hyd","Hyd","Hyd","Hyd","Hyd","Hyd"]}
b = pd.DataFrame(dict)
print(b)
  

       Name               EmailID  MobileNumber Address
0    hitesh      hitesh@gmail.com           999     Hyd
1    chandu  chandu2000@gmail.com           888     Hyd
2     akhil       akhil@gmail.com           777     Hyd
3        pk          pk@gmail.com           555     Hyd
4  megastar        mega@gmail.com           222     Hyd
5       Tan         tan@gmail.com           111     Hyd


In [0]:
#supermarket.csv- analysis(which product having higher % of selling )
#which product having least selling %

import panda as pd 
products=pd.read_csv('filename.csv')
print(products)


In [0]:
import pandas as pd 
product_sellingData=pd.read_csv('filename.csv',index_col=1)
print(product_selling)